_target_: src.models.components.measurement_op.CTSparseViewFanBeamOp
metadata_path: ${paths.data_dir}/fanbeam/scan_001_flat_fan_projections.tif
num_views: 32
image_size: 256
voxel_size: 0.7
fbp_filter: "shepp-logan"