_target_: src.models.dlir_module.EvalModule

guidence_module: ${guidence}

pipeline:
  _target_: src.models.components.pipelines.PixelReconstructionREDDiffPipeline
  _partial_: true
  scheduler:
    _target_: diffusers.DDPMScheduler
    # _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    prediction_type: "epsilon"
    clip_sample: True
    clip_sample_range: 1.0

unet:
  _target_: diffusers.UNet2DModel
  sample_size: 256
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  block_out_channels: [128, 256, 256, 512]
  center_input_sample: False
  downsample_padding: 1
  flip_sin_to_cos: True
  freq_shift: 0
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]

vqvae: null

unet_ckpt_path: ${paths.data_dir}/ckpt/ddpm_mayo_256/last.ckpt
vqvae_ckpt_path: null

im_out_dir: ${paths.eval_dir}/sr_test