_target_: src.models.dlir_ni_module.EvalModule

# guidence_module:
#   _partial_: true
#   _target_: src.models.components.guidence_modules.LatentDeepLatentIterativeReconstruct
#   scale: 0.01
#   optimizer:
#     _target_: src.models.components.guidence_modules.AdamOptimizer
#   # degrade_op: 
#   #   _target_: src.models.components.measurement_ops.SuperResolutionOp
#   #   scale_factor: 4
#   # degrade_op: 
#   #   _target_: src.models.components.measurement_ops.ColorizationOp
#   degrade_op: ${degrade_op}
#     # _target_: src.models.components.measurement_ops.CenterBoxInpaintingOP
#     # im_size: 256
#     # box_size: 128
#   # degrade_op:
#   #   _target_: src.models.components.measurement_ops.MotionBlurOp
#   #   kernel_size: 61
#   #   intensity: 0.5
#   #   device: "cuda"
#   # degrade_op:
#   #   _target_: src.models.components.measurement_ops.MotionBlurOp
#   #   kernel_size: 61
#   #   intensity: 0.5
#   #   device: "cuda"
#   # degrade_op:
#   #   _target_: src.models.components.measurement_ops.CTSparseViewOp
#   #   num_views: 64
#   #   det_shape: [512,]
#   #   im_shape: [256, 256]
#   #   angles: 3.1415926536 # 180 degrees
#     # angles: 1.5707963268 # 90 degrees
#     # angles: 0.7853981634 # 45 degrees
#   diff_module:
#     _target_: src.models.components.guidence_modules.NormModule
#     ord: 1
#     # _target_: torchmetrics.image.lpip.LearnedPerceptualImagePatchSimilarity
#   noise_op: ${noise_op}
    
guidence_module: ${guidence}

pipeline:
  _target_: src.models.components.pipelines.PixelReconstructionPipeline
  _partial_: true
  scheduler:
    _target_: diffusers.DDPMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    prediction_type: "epsilon"

unet:
  _target_: diffusers.UNet2DModel
  sample_size: 256
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  block_out_channels: [128, 128, 256, 256, 512, 512]
  center_input_sample: False
  downsample_padding: 0
  flip_sin_to_cos: false
  freq_shift: 1
  mid_block_scale_factor: 1
  norm_eps: 1e-6
  norm_num_groups: 32
  attention_head_dim: null
  act_fn: "silu"
  time_embedding_type: "positional"
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D","AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]

vqvae: null

unet_ckpt_path: ${paths.data_dir}ckpt/ddpm_celebahq_256/unet.bin
vqvae_ckpt_path: null

im_out_dir: ${paths.eval_dir}/ni_sr_test