_target_: src.models.klvae_2D_module.VAEModelLitModule

learning_rate: 1e-4
lr_g_factor: 0.2

model:
  _target_: src.models.components.kl_model.KLTrainModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: [ "DownEncoderBlock2D",
    "DownEncoderBlock2D",
    "DownEncoderBlock2D",
    "DownEncoderBlock2D"]
  up_block_types: [    "UpDecoderBlock2D",
    "UpDecoderBlock2D",
    "UpDecoderBlock2D",
    "UpDecoderBlock2D"]
  block_out_channels: [    128,
    256,
    512,
    512]
  # block_out_channels: [32, 64, 128, 384]
  latent_channels: 4
  norm_num_groups: 32