_target_: src.models.dlir_proj_module.EvalModule

guidence_module: ${guidence}

pipeline:
  _target_: src.models.components.pipelines.LatentReconstructionPipeline
  _partial_: true
  scheduler:
    # _target_: diffusers.DDPMScheduler
    # num_train_timesteps: 1000
    # beta_schedule: "linear"
    # prediction_type: "epsilon"
    _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    prediction_type: "epsilon"
  latents_height: 32
  latents_width: 32

unet:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 4
  out_channels: 4
  layers_per_block: 2
  block_out_channels: [128, 256, 256, 512]
  # block_out_channels: [64, 128, 128, 256]
  center_input_sample: False
  downsample_padding: 1
  flip_sin_to_cos: True
  freq_shift: 0
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]

vqvae:
  _target_: diffusers.models.VQModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "AttnDownEncoderBlock2D"]
  up_block_types: ["AttnUpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [64, 128, 256, 256, 512]
  latent_channels: 4
  vq_embed_dim: 4
  num_vq_embeddings: 16384

# unet_ckpt_path: ${paths.data_dir}ckpt/ldm_mayo_512/epoch_474.ckpt
# vqvae_ckpt_path: ${paths.data_dir}ckpt/ldm_mayo_512/epoch_474.ckpt

unet_ckpt_path: logs/unldm_512/runs/2023-12-07_18-44-27/checkpoints/last.ckpt
vqvae_ckpt_path: logs/unldm_512/runs/2023-12-07_18-44-27/checkpoints/last.ckpt

# unet_ckpt_path: logs/unldm_512/runs/2023-12-06_22-56-38/checkpoints/last.ckpt
# vqvae_ckpt_path: logs/unldm_512/runs/2023-12-06_22-56-38/checkpoints/last.ckpt


im_out_dir: ${paths.eval_dir}/sr_test