_target_: src.models.dlir_module.EvalModule

guidence_module: ${guidence}

pipeline:
  _target_: src.models.components.pipelines.LatentReconstructionVPredictionREDDiffPipeline
  _partial_: true
  scheduler:
    # _target_: diffusers.DDPMScheduler
    # # _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    # num_train_timesteps: 1000
    # beta_schedule: "linear"
    # prediction_type: "epsilon"
    # # clip_sample: True
    # # clip_sample_range: 1.0
    _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    prediction_type: "v_prediction"
  latents_height: 32
  latents_width: 32

unet:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 4
  out_channels: 4
  layers_per_block: 2
  # block_out_channels: [128, 256, 256, 512]
  block_out_channels: [320, 640, 800, 1280]
  center_input_sample: False
  downsample_padding: 1
  flip_sin_to_cos: True
  freq_shift: 0
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  down_block_types: ["AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]

vqvae:
  _target_: diffusers.models.VQModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "AttnDownEncoderBlock2D"]
  up_block_types: ["AttnUpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [64, 128, 256, 256, 512]
  latent_channels: 4
  vq_embed_dim: 4
  num_vq_embeddings: 16384

# unet_ckpt_path: ${paths.data_dir}ckpt/ldm_mayo_512/epoch_474.ckpt
# vqvae_ckpt_path: ${paths.data_dir}ckpt/ldm_mayo_512/epoch_474.ckpt

unet_ckpt_path: logs/unldm_seq_512_v_plus/runs/2024-01-26_17-34-17/checkpoints/epoch_924.ckpt
vqvae_ckpt_path: logs/unldm_seq_512_v_plus/runs/2024-01-26_17-34-17/checkpoints/epoch_924.ckpt


im_out_dir: ${paths.eval_dir}/sr_test