_target_: src.models.dlir_module.EvalModule

guidence_module: ${guidence}

pipeline:
  _target_: src.models.components.pipelines.LatentReconstructionPipeline
  _partial_: true
  scheduler:
    _target_: diffusers.DDPMScheduler
    # _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    prediction_type: "epsilon"
    # clip_sample: True
    # clip_sample_range: 1.5
  latents_height: 32
  latents_width: 32

unet:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 8
  out_channels: 8
  layers_per_block: 1
  block_out_channels: [128, 256, 256, 512]
  # block_out_channels: [64, 128, 128, 256]
  center_input_sample: False
  downsample_padding: 1
  flip_sin_to_cos: True
  freq_shift: 0
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]

vqvae:
  _target_: src.models.components.fsq_model.FSQTrainModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  # down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  # up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  # block_out_channels: [128, 128, 256, 256, 512]
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "AttnDownEncoderBlock2D"]
  up_block_types: ["AttnUpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [128, 128, 256, 512]
  latent_channels: 256
  vq_embed_dim: 8
  # num_vq_embeddings: 16384
  fsq_embed_dim: 8
  levels: [8, 8, 8, 6, 5]
  num_quantizers: 1

# logs/ldm_fsq/runs/2023-11-26_15-12-26/checkpoints/last.ckpt

unet_ckpt_path: ${paths.log_dir}ldm_fsq/runs/2023-11-26_15-12-26/checkpoints/last.ckpt
vqvae_ckpt_path: ${paths.log_dir}ldm_fsq/runs/2023-11-26_15-12-26/checkpoints/last.ckpt

im_out_dir: ${paths.eval_dir}/fsq_test