_target_: src.models.vss_infer_module_unet.EvalModule

guidance_module: ${guidance}

diffusion_mdoel:
  _target_: diffusers.UNet2DModel
  sample_size: 64
  in_channels: 4
  out_channels: 4
  layers_per_block: 2
  # block_out_channels: [128, 256, 256, 512]
  block_out_channels: [64, 128, 256, 512]
  center_input_sample: False
  downsample_padding: 1
  flip_sin_to_cos: True
  freq_shift: 0
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]


pipeline:
  _target_: src.models.components.pipelines.LatentReconstructionUNetVSSPipeline
  _partial_: true
  scheduler:
    # _target_: diffusers.DDPMScheduler
    # # _target_: src.models.components.schedulers.EnsembleDDIMScheduler
    # num_train_timesteps: 1000
    # beta_schedule: "linear"
    # prediction_type: "epsilon"
    # clip_sample: True
    # clip_sample_range: 1.5
    _target_: diffusers.DDPMScheduler
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: "linear"
    steps_offset: 0
    clip_sample: True
    prediction_type: "epsilon"
  latents_height: 64
  latents_width: 64

vqvae:
  _target_: src.models.components.vq_model.RQTrainModel
  # _target_: src.models.components.PlainVectorQuantizer.MultiScaleRQTrainModel
  act_fn: 'silu'
  block_out_channels: [128, 256, 512]
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  in_channels: 1
  out_channels: 1
  latent_channels: 4
  layers_per_block: 2
  norm_num_groups: 32
  num_vq_embeddings: 8192
  sample_size: 256
  vq_embed_dim: 4
  latents_scale: [1, 2, 4]

im_out_dir: ${paths.eval_dir}/mayo_recon_test

ckpt_path: ${paths.data_dir}/ckpt/last_v2.ckpt