_target_: src.models.vae_2D_module.VAEModelLitModule

learning_rate: 1e-4
lr_g_factor: 0.2
num_vq_embeddings: 16384

model:
  _target_: src.models.components.vq_model.VQTrainModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "AttnDownEncoderBlock2D"]
  up_block_types: ["AttnUpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [64, 128, 256, 256, 512]
  # block_out_channels: [32, 64, 128, 384]
  latent_channels: 4
  vq_embed_dim: 4
  num_vq_embeddings: 16384