_target_: src.models.vae_module.VAEModelLitModule

learning_rate: 5e-5
lr_g_factor: 0.2
num_vq_embeddings: 16384

model:
  _target_: src.models.components.vq_model_3d.VQ3DTrainModel
  in_channels: 1
  out_channels: 1
  layers_per_block: 1
  # down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  # up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  # block_out_channels: [128, 128, 256, 256, 512]
  down_block_types: ["DownBlock3D", "DownBlock3D", "DownBlock3D", "DownBlock3D",]
  up_block_types: ["UpBlock3D", "UpBlock3D", "UpBlock3D", "UpBlock3D"]
  block_out_channels: [32, 64, 128, 384]
  latent_channels: 4
  vq_embed_dim: 4
  num_vq_embeddings: 16384