_target_: src.models.components.guidence_modules.PixelManifoldConstraintGradient
diff_module:
  _target_: src.models.components.guidence_modules.NormModule
  ord: 2
scale: 5

degrade_op: ${degrade_op}
noise_op: ${noise_op}
